# typed: false
# frozen_string_literal: true

# Moo, the keyboard launcher. Universal (Apple silicon and Intel), signed and notarized.
# Generated by .github/workflows/update-formulas.yml; edits here are overwritten.
cask "moo" do
  version "0.9.0"
  sha256 "26ca102c2dc6f7dac0684d3fd553cdf22124a02263751a3e896ea1beebb6a233"

  url "https://github.com/moomoi/moo/releases/download/v#{version}/Moo-macos-universal.dmg"
  name "Moo"
  desc "Keyboard launcher for apps, files, the clipboard, AI and more"
  homepage "https://moo.moi"

  livecheck do
    url :url
    strategy :github_latest
  end

  depends_on macos: ">= :sonoma"

  app "Moo.app"
  # The app binary is also the `moo` command line client.
  binary "#{appdir}/Moo.app/Contents/MacOS/moo"

  uninstall quit: "moi.moo.launcher"

  zap trash: [
    "~/Library/Application Support/Moo",
    "~/Library/Caches/Moo",
    "~/Library/Preferences/moi.moo.launcher.plist",
  ]
end
